### ISSUE TITLE
Error: Failed to load SQLite3 Dynamic Library

### ISSUE THREAD

**Issue by DavidPesta** [denodrivers/sqlite3#114]
On Ubuntu 22.04.
The same thing happens for both 0.8.0 and also 0.10.0:
```
$ deno run --allow-all sqlite3.ts
Downloading https://github.com/denodrivers/sqlite3/releases/download/0.10.0/libsqlite3.so
error: Uncaught (in promise) Error: Failed to load SQLite3 Dynamic Library
  throw new Error("Failed to load SQLite3 Dynamic Library", { cause: e });
        ^
    at https://deno.land/x/sqlite3@0.10.0/src/ffi.ts:631:9
    at eventLoopTick (ext:core/01_core.js:178:11)
Caused by: TypeError: Deno.dlopen is not a function
    at dlopen (https://deno.land/x/plug@1.0.1/mod.ts:155:15)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async https://deno.land/x/sqlite3@0.10.0/src/ffi.ts:614:7
```

**Comment by DjDeveloperr** [comment]
Can you try using —unstable flag?

**Comment by DavidPesta** [comment]
That works. I forgot about that in the Usage section. :sweat_smile:
