### ISSUE TITLE
Transactions not working correctly

### ISSUE THREAD

**Issue by ashersaupingomez** [denodrivers/sqlite3#20]
Currently, transactions are not working when using either named parameters or un-named parameters.
**Setup:**
```ts
import { Database } from "https://deno.land/x/sqlite3@0.3.0/mod.ts";

const db = new Database(":memory:");

db.execute(`
  CREATE TABLE people (
    name TEXT NOT NULL
  );
`);
```
**Named parameters:**
```ts
db.execute(`
  BEGIN TRANSACTION;
  INSERT INTO people (name)
  VALUES (:name);
  COMMIT;
`, { name: "John Doe" });
```
Throws:
```bash
error: Uncaught Error: Couldn't find index for ':name'
      throw new Error(`Couldn't find index for '${name}'`);
            ^
    at PreparedStatement.bindParameterIndex (https://deno.land/x/sqlite3@0.3.0/src/database.ts:386:13)
    at PreparedStatement.bindAllNamed (https://deno.land/x/sqlite3@0.3.0/src/database.ts:521:26)
    at Database.execute (https://deno.land/x/sqlite3@0.3.0/src/database.ts:148:14)
```

**Un-named parameters:**
```ts
db.execute(`
  BEGIN TRANSACTION;
  INSERT INTO people (name)
  VALUES (?);
  COMMIT;
`, "John Doe");
```
Throws:
```bash
error: Uncaught Error: (25) column index out of range: column index out of range
    throw new Error(`(${result}) ${sqlite3_errstr(result)}: ${msg}`);
          ^
    at unwrap_error (https://deno.land/x/sqlite3@0.3.0/src/ffi.ts:368:11)
    at sqlite3_bind_text (https://deno.land/x/sqlite3@0.3.0/src/ffi.ts:448:3)
    at PreparedStatement.bind (https://deno.land/x/sqlite3@0.3.0/src/database.ts:479:9)
    at PreparedStatement.bindAll (https://deno.land/x/sqlite3@0.3.0/src/database.ts:515:12)
    at Database.execute (https://deno.land/x/sqlite3@0.3.0/src/database.ts:150:14)
```
Deno version: 1.17.3 (release, x86_64-apple-darwin)
Module version: 0.3.0
macOS version: 12.1
SQLite version: 3.37.2

**Comment by DjDeveloperr** [comment]
You need to split `begin transaction` & `commit` to separate queries

![image](https://user-images.githubusercontent.com/43033058/150284508-5daf1310-786e-47d1-99b5-4183b9d372c9.png)

**Comment by ashersaupingomez** [comment]
Ok - that’s fair. Thank you 🙏🏾

**Comment by waynebloss** [comment]
So, just to be clear - I believe that you can execute multiple statements with `db.execute`, but just not the `BEGIN TRANSACTION` and `COMMIT` statements, right?

Because this is working for me:

```ts
db.execute(
      `INSERT OR IGNORE INTO settings(name, value) VALUES('setup', 1);
INSERT OR IGNORE INTO settings(name, value) VALUES('test', 'hello');`,
    );
```

I am wondering if multiple `PRAGMA` statements can be made in one call to `db.execute()` but I will find out soon on my own.
