### ISSUE TITLE
bind NaN got exception

### ISSUE THREAD

**Issue by codehz** [denodrivers/sqlite3#21]
(and it should be treat as null)

TypeError - Expected FFI argument to be a double, but got Null

at Object.opSync (deno:core/01_core.js:149:12)
    at Object.DynamicLibrary.symbols.<computed> [as sqlite3_bind_double] (deno:ext/ffi/00_ffi.js:253:33)       
    at sqlite3_bind_double (https://deno.land/x/sqlite3@0.3.0/src/ffi.ts:495:30)
    at PreparedStatement.bind (https://deno.land/x/sqlite3@0.3.0/src/database.ts:436:11)
    at PreparedStatement.bindAll (https://deno.land/x/sqlite3@0.3.0/src/database.ts:515:12)

**Comment by DjDeveloperr** [comment]
Released 0.3.1 with fix
