### ISSUE TITLE
Doesn't work on Linux

### ISSUE THREAD

**Issue by ralyodio** [denodrivers/sqlite3#46]
```
$ deno run -A ./app.ts  
Download https://cdn.skypack.dev/error/buffer?from=vfile
error: Uncaught Error: Native SQLite3 library not found, try installing SQLite3. If you have an existing installation, either add it to path or set the `DENO_SQLITE_PATH` environment variable.
  const error = new Error(
                ^
    at https://deno.land/x/sqlite3@0.4.4/src/ffi.ts:426:17
Caused by: TypeError: Deno.dlopen is not a function
    at https://deno.land/x/sqlite3@0.4.4/src/ffi.ts:420:14
➜  app git:(master) ✗ 
$ deno -V             
deno 1.25.0
```

Manjaro/arch and Ubuntu. Neither work all of a sudden.

**Comment by niklaskorz** [comment]
You have to run it with `--unstable --allow-ffi`, otherwise `Deno.dlopen` is unavailable.

**Comment by DjDeveloperr** [comment]
As mentioned above, `--unstable` is missing. Closing. And there's some breaking changes in Deno 1.25 which actually broke the library some other way, which #44 will be fixing along with rewrite
