### ISSUE TITLE
Getting this error for some reason

### ISSUE THREAD

**Issue by ralyodio** [denodrivers/sqlite3#62]
```
[uncaught application error]: TypeError - Invalid CString pointer, not valid UTF-8

request: { url: "http://briskreader.com/api/1/recent", method: "GET", hasBody: false }
response: { status: 404, type: undefined, hasBody: false, writable: true }

    at getColumn (https://deno.land/x/sqlite3@0.5.3/src/statement.ts:72:14)
    at eval (eval at #allNoArgs (https://deno.land/x/sqlite3@0.5.3/src/statement.ts:261:30), <anonymous>:6:20)
    at Statement.#allNoArgs [as all] (https://deno.land/x/sqlite3@0.5.3/src/statement.ts:423:19)
    at file:///home/ubuntu/www/briskreader.com/app/app.ts:248:5
    at dispatch (https://deno.land/x/oak@v11.1.0/middleware.ts:41:13)
    at https://deno.land/x/oak@v11.1.0/router.ts:1229:20
    at dispatch (https://deno.land/x/oak@v11.1.0/middleware.ts:41:13)
    at composedMiddleware (https://deno.land/x/oak@v11.1.0/middleware.ts:44:12)
    at dispatch (https://deno.land/x/oak@v11.1.0/router.ts:1235:28)
    at dispatch (https://deno.land/x/oak@v11.1.0/middleware.ts:41:13)
```

It's just doing a select:

```
	.get('/recent', async (context) => {
		const links = await context.state.db
			.prepare(
				'SELECT url, title, excerpt, created_at, count FROM urls ORDER BY created_at DESC LIMIT 50'
			)
			.all();

		context.response.body = links;
	})
```

**Comment by DjDeveloperr** [comment]
Fix has been implemented, release is pending (#61). See previous issue for more context #57 
For now you can import directly from https://raw.githubusercontent.com/denodrivers/sqlite3/d597bc5c9308bb16018534f63143a636b2ddb5eb/mod.ts (note that this fix only prevents corruption, you will still have to fix the corrupted row if it is giving error)

**Comment by ralyodio** [comment]
any idea how i can find the corrupted row?

**Comment by DjDeveloperr** [comment]
Run the query in SQLite CLI, it'll show garbled values where it is corrupted.

**Comment by DjDeveloperr** [comment]
BTW now you can import normally from https://deno.land/x/sqlite3@0.6.0/mod.ts - corruption issues will not appear anymore, just need to fix current data for now. If you need any help with that feel free to comment further on this issue. If it is resolved, let me know. Thanks

**Comment by ralyodio** [comment]
Installed. I'll let you know if I see it again. Closing issue for now.

**Comment by ralyodio** [comment]
Sorry, re-opening. app won't start now.

```
error: Uncaught Error: Native SQLite3 library not found, try installing SQLite3. If you have an existing installation, either add it to path or set the `DENO_SQLITE_PATH` environment variable.
  const error = new Error(
                ^
    at https://deno.land/x/sqlite3@0.6.0/src/ffi.ts:450:17
Caused by: CacheError: Not Found
    at protocolHttp (https://deno.land/x/cache@0.2.13/file_fetcher.ts:23:11)
    at async fetchFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:45:14)
    at async FileWrapper.fetch (https://deno.land/x/cache@0.2.13/file.ts:95:18)
    at async FileWrapper.get (https://deno.land/x/cache@0.2.13/file.ts:113:12)
    at async cache (https://deno.land/x/cache@0.2.13/cache.ts:67:10)
    at async Wrapper.cache (https://deno.land/x/cache@0.2.13/cache.ts:21:12)
    at async download (https://deno.land/x/plug@0.5.2/plug.ts:107:16)
    at async prepare (https://deno.land/x/plug@0.5.2/plug.ts:116:16)
    at async https://deno.land/x/sqlite3@0.6.0/src/ffi.ts:434:12
```

**Comment by DjDeveloperr** [comment]
Use 0.6.1 instead

**Comment by ralyodio** [comment]
That worked. Tanks.
