### ISSUE TITLE
Error: Native SQLite3 library not found, try installing SQLite3

### ISSUE THREAD

**Issue by korywka** [denodrivers/sqlite3#63]
After upgrade to `0.6.0` from `0.5.2` (OSX 12.6)

```
Download https://github.com/denodrivers/sqlite3/releases/download/v0.6.0/libsqlite3_aarch64.dylib
error: Uncaught (in promise) Error: Native SQLite3 library not found, try installing SQLite3. If you have an existing installation, either add it to path or set the `DENO_SQLITE_PATH` environment variable.
  const error = new Error(
                ^
    at https://deno.land/x/sqlite3@0.6.0/src/ffi.ts:450:17
Caused by: CacheError: Not Found
    at protocolHttp (https://deno.land/x/cache@0.2.13/file_fetcher.ts:23:11)
    at async fetchFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:45:14)
    at async FileWrapper.fetch (https://deno.land/x/cache@0.2.13/file.ts:95:18)
    at async FileWrapper.get (https://deno.land/x/cache@0.2.13/file.ts:113:12)
    at async cache (https://deno.land/x/cache@0.2.13/cache.ts:67:10)
    at async Wrapper.cache (https://deno.land/x/cache@0.2.13/cache.ts:21:12)
    at async download (https://deno.land/x/plug@0.5.2/plug.ts:107:16)
    at async prepare (https://deno.land/x/plug@0.5.2/plug.ts:116:16)
    at async https://deno.land/x/sqlite3@0.6.0/src/ffi.ts:434:12
```

I installed it with brew:

```
which sqlite3
/usr/bin/sqlite3
```

And added it to profiles:

```
echo 'export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"' >> ~/.zshrc
```

But error is the same. `0.5.2` worked ok without even sqlite3 installed with brew.

Please, can someone give a hint how to fix it.

**Comment by DjDeveloperr** [comment]
Looks like there's a typo in code where it looks up version with `v` instead of without it... I'll release 0.6.1 patch soon

**Comment by DjDeveloperr** [comment]
Try 0.6.1 @korywka

**Comment by korywka** [comment]
@DjDeveloperr yep, now it works. Thanks for such quick help.
